apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: dev
  labels:
    app: myapp
    environment: dev
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30081
